version: "3.3"

services:
  web:
    image: golang:1.10
    volumes:
      - .:/go/src/github.com/jianhan/shopify_repos
    working_dir: /go/src/github.com/jianhan/shopify_repos
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      CACHE_DURATION: 60
      REPO_USER: Shopify
      ADDRESS_PORT: :8080
